// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJrNpe_f8xmJKfUUmYSLHc4xmfBTgYk4',
    appId: '1:543175099559:web:0a1e720aa97d0c4d6d8782',
    messagingSenderId: '543175099559',
    projectId: 'sup4-dev-trello',
    authDomain: 'sup4-dev-trello.firebaseapp.com',
    storageBucket: 'sup4-dev-trello.firebasestorage.app',
    measurementId: 'G-SCD51FRM91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3dHsQkGtvEOzlhs7mCF0XEhWIQPm4Pg',
    appId: '1:709777904807:android:c69346d58a4570d37e3782',
    messagingSenderId: '709777904807',
    projectId: 'sup4-dev-trello-ef2e7',
    storageBucket: 'sup4-dev-trello-ef2e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGBpZpBzXJqgW61TI3NKUSMY9cd8iW_0A',
    appId: '1:709777904807:ios:46deabeba4979b517e3782',
    messagingSenderId: '709777904807',
    projectId: 'sup4-dev-trello-ef2e7',
    storageBucket: 'sup4-dev-trello-ef2e7.firebasestorage.app',
    iosBundleId: 'com.example.sup4DevTrello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGBpZpBzXJqgW61TI3NKUSMY9cd8iW_0A',
    appId: '1:709777904807:ios:46deabeba4979b517e3782',
    messagingSenderId: '709777904807',
    projectId: 'sup4-dev-trello-ef2e7',
    storageBucket: 'sup4-dev-trello-ef2e7.firebasestorage.app',
    iosBundleId: 'com.example.sup4DevTrello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsjNt3xUGBu5JtrlR6iPJ2SO8-9QN5mI8',
    appId: '1:709777904807:web:2b9a3476b675128a7e3782',
    messagingSenderId: '709777904807',
    projectId: 'sup4-dev-trello-ef2e7',
    authDomain: 'sup4-dev-trello-ef2e7.firebaseapp.com',
    storageBucket: 'sup4-dev-trello-ef2e7.firebasestorage.app',
    measurementId: 'G-MH4JNP3X9Q',
  );
}
